### ISSUE TITLE
CSS实现元素水平垂直居中的方式

### ISSUE THREAD

**Issue by leebyte** [leebyte/Notes#1]
### 1. 绝对定位
_使用absolute进行水平垂直居中定位时，应确保其父元素的position属性为relative_

```css
/*绝对定位元素公共样式代码抽离*/
.abs-ele {
    position: absolute;
    height: 100px;
    width: 100px;
    background-color: #f0ad4e;
    border: 1px solid #ff7e31;
}
```
* 1.1. 绝对定位+Margin负值  
_适用于：定高定宽元素。若居中元素为动态赋值，可借助JS计算left&top的位移值进行赋值计算。_

```html
<div class="abs-ele abs_center1"></div>
```

```css
.abs_center1 {
    left: 50%;
    top: 50%;
    margin-left: -50px;/* 居中元素宽/2 */
    margin-top: -50px;/* 居中元素高/2 */
}

```

* 1.2. 绝对定位+Transform位移  
_transform为CSS3新增属性，兼容IE9及以上版本浏览器。适用于：定高定宽元素&未知宽高元素_  
_兼容性查询网站：https://www.caniuse.com_  
```html
<div class="abs-ele abs_center2">Center2</div>
```
```css
.abs_center2 {
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
}
```  

* 1.3. 绝对定位+Margin:auto   
_上右下左绝对定位均为0。适用于：定高定宽元素&未知宽高元素_  
```html
<div class="abs-ele abs_center3">Center3</div>
```
```css
.abs_center3 {
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
}
```  

### 2. Flex布局  
_Flex(弹性布局，全拼： Flexible Box),是一种灵活性的布局方式，可简便、完整、响应式地实现各种页面布局，存在一定的浏览器兼容性问题；适用于：定高定宽元素&未知宽高元素。_  
_更多Flex芝士点：https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex_

```html
/*定义一个flex容器*/
<div class="flex-box">
    <div class="flex-center-ele">Center4</div>
</div>
```
```css
.flex-box {
    display: flex;
    height: 300px;
    width: 300px;
    align-items: center;/*横轴居中对齐*/
    justify-content: center;/*主轴居中对齐*/
    border: 1px solid #0e77ca;
}
.flex-center-ele {
    height: 100px;
    width: 100px;
    line-height: 100px;
    text-align: center;
    background-color: #f0ad4e;
    border: 1px solid #ff7e31;
}
```  

### 3.Grid布局
_类似于Flex布局，都需要创建一个根容器，容器内是Grid的项目，可以指定容器内每个项目的位置；但不同于Flex布局的是Grid是一个二维布局，功能相对强大于一维布局的Flex布局。适用于：定高定宽元素&未知宽高元素。_

```html
<div class="grid-box">
    <div class="grid-center-ele">Center5</div>
</div>
```
```css
.grid-box {
    display: grid;
    height: 300px;
    width: 300px;
    justify-items:center;
    align-items:center;
    border: 1px solid #0e77ca;
}
.grid-center-ele {
    height: 100px;
    width: 100px;
    line-height: 100px;
    text-align: center;
    background-color: #f0ad4e;
    border: 1px solid #ff7e31;
}
```  
### 4. 伪造一个Table氛围  
_适用于：定高定宽元素&未知宽高元素._
```html
<div class="table-box">
    <div class="table-center-cell">Center6</div>
</div>
```
```css
.table-box {
    display: table-cell;
    height: 300px;
    width: 300px;
    border: 1px solid #0e77ca;
    vertical-align: middle;
    text-align: center;
}
.table-center-cell {
    display: inline-block;
    height: 100px;
    width: 100px;
    line-height: 100px;
    text-align: center;
    background-color: #f0ad4e;
    border: 1px solid #ff7e31;
}
```  
## 【扩展】

1. 单行文本水平垂直居中
```css
text-align:center;
line-height:100px;/*文本父元素高度*/
```
